/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as DestinationGuideRouteImport } from './routes/destination-guide'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as StayRouteImport } from './routes/stay'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as DiningSlugRouteImport } from './routes/dining.$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as VillasSlugRouteImport } from './routes/villas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationGuideRoute = DestinationGuideRouteImport.update({
  id: '/destination-guide',
  path: '/destination-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DiningSlugRoute = DiningSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiningRoute,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const VillasSlugRoute = VillasSlugRouteImport.update({
  id: '/villas/$slug',
  path: '/villas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/destination-guide': typeof DestinationGuideRoute
  '/dining': typeof DiningRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/our-story': typeof OurStoryRoute
  '/stay': typeof StayRoute
  '/sustainability': typeof SustainabilityRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/villas/$slug': typeof VillasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/destination-guide': typeof DestinationGuideRoute
  '/dining': typeof DiningRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/our-story': typeof OurStoryRoute
  '/stay': typeof StayRoute
  '/sustainability': typeof SustainabilityRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/villas/$slug': typeof VillasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/destination-guide': typeof DestinationGuideRoute
  '/dining': typeof DiningRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/our-story': typeof OurStoryRoute
  '/stay': typeof StayRoute
  '/sustainability': typeof SustainabilityRoute
  '/wellness': typeof WellnessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/villas/$slug': typeof VillasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/destination-guide'
    | '/dining'
    | '/experiences'
    | '/membership'
    | '/offers'
    | '/our-story'
    | '/stay'
    | '/sustainability'
    | '/wellness'
    | '/admin'
    | '/portal'
    | '/dining/$slug'
    | '/experiences/$slug'
    | '/villas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/destination-guide'
    | '/dining'
    | '/experiences'
    | '/membership'
    | '/offers'
    | '/our-story'
    | '/stay'
    | '/sustainability'
    | '/wellness'
    | '/admin'
    | '/portal'
    | '/dining/$slug'
    | '/experiences/$slug'
    | '/villas/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/destination-guide'
    | '/dining'
    | '/experiences'
    | '/membership'
    | '/offers'
    | '/our-story'
    | '/stay'
    | '/sustainability'
    | '/wellness'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/dining/$slug'
    | '/experiences/$slug'
    | '/villas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  DestinationGuideRoute: typeof DestinationGuideRoute
  DiningRoute: typeof DiningRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  MembershipRoute: typeof MembershipRoute
  OffersRoute: typeof OffersRoute
  OurStoryRoute: typeof OurStoryRoute
  StayRoute: typeof StayRoute
  SustainabilityRoute: typeof SustainabilityRoute
  WellnessRoute: typeof WellnessRoute
  VillasSlugRoute: typeof VillasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-guide': {
      id: '/destination-guide'
      path: '/destination-guide'
      fullPath: '/destination-guide'
      preLoaderRoute: typeof DestinationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dining/$slug': {
      id: '/dining/$slug'
      path: '/$slug'
      fullPath: '/dining/$slug'
      preLoaderRoute: typeof DiningSlugRouteImport
      parentRoute: typeof DiningRoute
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/villas/$slug': {
      id: '/villas/$slug'
      path: '/villas/$slug'
      fullPath: '/villas/$slug'
      preLoaderRoute: typeof VillasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DiningRouteChildren {
  DiningSlugRoute: typeof DiningSlugRoute
}

const DiningRouteChildren: DiningRouteChildren = {
  DiningSlugRoute: DiningSlugRoute,
}

const DiningRouteWithChildren =
  DiningRoute._addFileChildren(DiningRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  DestinationGuideRoute: DestinationGuideRoute,
  DiningRoute: DiningRouteWithChildren,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  MembershipRoute: MembershipRoute,
  OffersRoute: OffersRoute,
  OurStoryRoute: OurStoryRoute,
  StayRoute: StayRoute,
  SustainabilityRoute: SustainabilityRoute,
  WellnessRoute: WellnessRoute,
  VillasSlugRoute: VillasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
